### ISSUE TITLE
Cannot read property 'log' of undefined (test.ctx.log on main.js:288)

### ISSUE THREAD

**Issue by carpiediem** [Gauge/html_table_reporter#6]
I'm getting an error that I can't figure out.  I have a long series of unit tests in 24 files.  When I run them through mocha using the default reporter, the process finishes normally (some tests passing, some failing, as I expect).  When I use `-R good-mocha-html-reporter` on individual files, they work fine too.  But when I use this reporter on a full test run (which takes a while), the process aborted with the error below.  No HTML report was generated by the full run.

Is there a maximum length to the report that I'm surpassing?  Maybe something breaks when Windows goes into sleep mode?  Any other ideas?

```
C:\dev\fo-rest-api>npm test

> fo-rest-api@0.6.0 test C:\dev\fo-rest-api
> mocha test/bootstrap.test.js test/common.js test/unit/*/*.test.js

Mocha HTML Table Reporter v2.0.0
NOTE: Tests sequence must complete to generate html report
Run Mode: VERBOSE

AccountController
  /account
    √ should accept API key <2703>
    √ should return expected attributes <2437>

...lots more...

    x should return client orders <NaN>
      |Test Logs|


      |Error Message|
TypeError: undefined is not a function
OrganisationController
C:\dev\fo-rest-api\node_modules\good-mocha-html-reporter\main.js:288
                test.log = test.ctx.log;
                                   ^
TypeError: Cannot read property 'log' of undefined
    at Runner.<anonymous> (C:\dev\fo-rest-api\node_modules\good-mocha-html-reporter\main.js:288:36)
    at Runner.emit (events.js:110:17)
    at Runner.fail (C:\dev\fo-rest-api\node_modules\mocha\lib\runner.js:233:8)
    at Runner.uncaught (C:\dev\fo-rest-api\node_modules\mocha\lib\runner.js:683:12)
    at process.uncaught (C:\dev\fo-rest-api\node_modules\mocha\lib\runner.js:783:10)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
npm ERR! Test failed.  See above for more details.
```

This is my mocha.opts file:

```
-R good-mocha-html-reporter
-p reports/mocha.html
```

**Comment by Gauge** [comment]
That error message indicates that the ctx variable was not created for the test. This is not something i have seen before.
1. What version of mocha are you using?
2. If there is any way you can show me the test that is failing or a similar failing test, i would lie to see it.
3. Are you using the log attribute at all in your tests?

**Comment by carpiediem** [comment]
1. 2.4.5
2. I've tried this several times and it has actually completed successfully twice now.  When it fails, it does so on a different test each time, so I don't think the tests themselves are a factor.
3. Do you mean this.log, as in your documentation, then no.  There might be a console.log() or two somewhere in the tests, but even that is unlikely.

**Comment by DSigmund** [comment]
Same for me here...
But i got this every time
`
/usr/lib/node_modules/good-mocha-html-reporter/main.js:288
                test.log = test.ctx.log;
                                   ^

TypeError: Cannot read property 'log' of undefined
    at Runner.<anonymous> (/usr/lib/node_modules/good-mocha-html-reporter/main.js:288:36)
    at emitTwo (events.js:106:13)
    at Runner.emit (events.js:191:7)
    at Runner.fail (/usr/lib/node_modules/mocha/lib/runner.js:233:8)
    at Runner.uncaught (/usr/lib/node_modules/mocha/lib/runner.js:678:12)
    at process.uncaught (/usr/lib/node_modules/mocha/lib/runner.js:778:10)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:254:26)
`

**Comment by Gauge** [comment]
Alright, I have pushed out a new build with some tweaks to how i manage ctx.log. I hope that solves your problems but as i was unable to reproduce the issue myself i cant be sure. 

Also Github was apparently a few commits behind npmjs. If you have been using the reporter from here, there are a lot of quality of life changes i made.

Let me know if the issue persists and how, if at all, it changes.
